# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hmS4w359zNimJe9LDlLX0wuTnE3FjcmA
"""

a=int(input("Enter cost of first element:"))
b=int(input("Enter cost of second element: "))
c=int(input("Enter cost of third element:"))
d=a+b+c
e=d-(d*(10/100))
if(d>50):
  print("Final cost after applying discount : ",e)
else:
    print("Final cost without applying disount :",d)